extends Node

const DEFAULT_LANGUAGE_CODE := "en"

const LANGUAGE_NAMES := {
	"en": "English",
	"ru": "Русский",
	"de": "Deutsch",
	"fr": "Français",
	"es": "Español",
	"fi": "Suomi",
	"sv": "Svenska"
}

const TRANSLATIONS := {
	"en": {
		"main_title": "Royal Lines",
		"main_subtitle": "Chess movement. Lines puzzle. 5 in a row.",
		"play": "Play",
		"how_to_play": "How to Play",
		"settings": "Settings",
		"quit": "Quit",
		"back": "Back",
		"close": "Close",
		"sound": "Sound",
		"vibration": "Vibration",
		"theme": "Theme",
		"language": "Language",
		"on": "On",
		"off": "Off",
		"sound_on": "Sound: On",
		"sound_off": "Sound: Off",
		"vibration_on": "Vibration: On",
		"vibration_off": "Vibration: Off",
		"theme_default": "Default",
		"theme_neon": "Neon",
		"how_to_play_text": "[font_size=46][b]Goal[/b][/font_size]\nMove chess pieces to create lines of 5 or more matching pieces to clear them and score points.\n\n[font_size=46][b]Movement[/b][/font_size]\n- Click a piece to select it\n- Valid empty cells are highlighted\n- Click a highlighted cell to move\n- Pieces move by chess-inspired rules\n\n[font_size=46][b]Clearing Lines[/b][/font_size]\n[color=RED]Color line:[/color] 5 or more pieces of the same color\n[color=GREEN]Type line:[/color] 5 or more pieces of the same type\n[color=YELLOW]Combo:[/color] A line that matches both color and type\n\n[font_size=46][b]Turn Flow[/b][/font_size]\n- Start with 3 random pieces\n- After each move, 3 more pieces spawn\n- If the board fills up or no meaningful moves remain, the game ends\n\n[font_size=46][b]Kingdom Badges[/b][/font_size]",
		"badge_progression_summary": "Maximum completed level in the kingdom.\nEmpty / Bronze / Silver / Gold",
		"badge_tactical_summary": "Measures how well you stand without sacrificing pieces.\nEmpty / Bronze / Silver / Gold",
		"badge_campaign_summary": "Your campaign performance.\nEmpty / Bronze / Silver / Gold",
		"score": "Score",
		"best": "Best",
		"your_best": "Your best",
		"final_score": "Final Score",
		"game_paused": "Game paused.",
		"resume": "Resume",
		"reset": "Reset",
		"main_menu": "Main Menu",
		"game_over": "GAME OVER",
		"session_complete": "Session complete",
		"play_again": "Play Again",
		"level_start_default": "Starting level #{number}",
		"level_start_default_theme": "Let the fight begin!",
		"level_start_neon_theme": "Let's shed some light on the dark.",
		"level_complete": "Level {number} complete!",
		"level_complete_short": "Level complete",
		"trap_disappeared": "Trapped by {trap} -{cost} :(",
		"trap_swallow_name": "Big Swamp",
		"trap_swallow_description": "I'll chew you up and spit you out.",
		"sacrifice": "{piece} Sacrifice",
		"piece_pawn": "Pawn",
		"piece_knight": "Knight",
		"piece_bishop": "Bishop",
		"piece_rook": "Rook",
		"piece_queen": "Queen",
		"piece_king": "King",
		"piece_generic": "Piece",
		"color_line": "Color Line",
		"row_6": "6 in Row",
		"row_7": "7 in Row",
		"row_8": "8 in Row",
		"long_line": "Long Line",
		"pawn_formation": "Pawn Formation",
		"knight_line": "Knight Line",
		"bishop_chain": "Bishop Chain",
		"rook_formation": "Rook Formation",
		"queen_formation": "Queen Formation",
		"typed_line": "Typed Line",
		"united_knights": "United Knights",
		"united_bishops": "United Bishops",
		"united_rooks": "United Rooks",
		"united_forces": "United Forces",
			"move_hint_move_one": "move to 1 cell",
			"move_hint_move_many": "move to {count} cells",
			"move_hint_attack_one": "attack 1 piece",
			"move_hint_attack_many": "attack {count} pieces",
			"move_hint_move_only": "{piece} can {moves}.",
			"move_hint_attack_only": "{piece} can {attacks}.",
			"move_hint_move_attack": "{piece} can {moves} and {attacks}.",
			"move_hint_blocked": "{piece} is blocked."
	},
	"ru": {
		"main_title": "Royal Lines",
		"main_subtitle": "Шахматные ходы. Головоломка Lines. 5 в ряд.",
		"play": "Играть",
		"how_to_play": "Как играть",
		"settings": "Настройки",
		"quit": "Выйти",
		"back": "Назад",
		"close": "Закрыть",
		"sound": "Звук",
		"vibration": "Вибрация",
		"theme": "Тема",
		"language": "Язык",
		"on": "Вкл.",
		"off": "Выкл.",
		"sound_on": "Звук: вкл.",
		"sound_off": "Звук: выкл.",
		"vibration_on": "Вибрация: вкл.",
		"vibration_off": "Вибрация: выкл.",
		"theme_default": "Стандартная",
		"theme_neon": "Неон",
		"how_to_play_text": "[b]Цель:[/b]\nПеремещайте шахматные фигуры, чтобы создавать линии из 5 или более одинаковых фигур, убирать их и получать очки.\n\n[b]Ходы:[/b]\n- Нажмите на фигуру, чтобы выбрать ее\n- Доступные пустые клетки подсвечиваются\n- Нажмите на подсвеченную клетку, чтобы сделать ход\n- Фигуры ходят по правилам, вдохновленным шахматами\n\n[b]Очистка линий:[/b]\n[color=RED]Линия цвета:[/color] 5 или более фигур одного цвета\n[color=GREEN]Линия типа:[/color] 5 или более фигур одного типа\n[color=YELLOW]Комбо:[/color] линия совпадает и по цвету, и по типу\n\n[b]Ход игры:[/b]\n- В начале есть 3 случайные фигуры\n- После каждого хода появляются еще 3 фигуры\n- Если поле заполнено или полезных ходов больше нет, игра заканчивается\n\n[b]Знаки королевства:[/b]",
		"badge_progression_summary": "Максимальный завершенный уровень в королевстве.\nПусто / Бронза / Серебро / Золото",
		"badge_tactical_summary": "Показывает, как хорошо вы держитесь без жертв фигур.\nПусто / Бронза / Серебро / Золото",
		"badge_campaign_summary": "Ваш результат в кампаниях.\nПусто / Бронза / Серебро / Золото",
		"score": "Счет",
		"best": "Рекорд",
		"your_best": "Ваш рекорд",
		"final_score": "Итоговый счет",
		"game_paused": "Игра на паузе.",
		"resume": "Продолжить",
		"reset": "Сброс",
		"main_menu": "Главное меню",
		"game_over": "ИГРА ОКОНЧЕНА",
		"session_complete": "Сессия завершена",
		"play_again": "Играть снова",
		"level_start_default": "Уровень #{number}",
		"level_start_default_theme": "Да начнется битва!",
		"level_start_neon_theme": "Прольем свет на тьму.",
		"level_complete": "Уровень {number} пройден!",
		"level_complete_short": "Уровень пройден",
		"trap_disappeared": "Попался в {trap} -{cost} :(",
		"trap_swallow_name": "Большая трясина",
		"trap_swallow_description": "Пережую и выплюну",
		"sacrifice": "{piece}: жертва",
		"piece_pawn": "Пешка",
		"piece_knight": "Конь",
		"piece_bishop": "Слон",
		"piece_rook": "Ладья",
		"piece_queen": "Ферзь",
		"piece_king": "Король",
		"piece_generic": "Фигура",
		"color_line": "Линия цвета",
		"row_6": "6 в ряд",
		"row_7": "7 в ряд",
		"row_8": "8 в ряд",
		"long_line": "Длинная линия",
		"pawn_formation": "Строй пешек",
		"knight_line": "Линия коней",
		"bishop_chain": "Цепь слонов",
		"rook_formation": "Строй ладей",
		"queen_formation": "Строй ферзей",
		"typed_line": "Линия типа",
		"united_knights": "Объединенные кони",
		"united_bishops": "Объединенные слоны",
		"united_rooks": "Объединенные ладьи",
		"united_forces": "Объединенные силы",
			"move_hint_move_one": "пойти на 1 клетку",
			"move_hint_move_many": "пойти на {count} клеток",
			"move_hint_attack_one": "атаковать 1 фигуру",
			"move_hint_attack_many": "атаковать {count} фигур",
			"move_hint_move_only": "{piece} может {moves}.",
			"move_hint_attack_only": "{piece} может {attacks}.",
			"move_hint_move_attack": "{piece} может {moves} и {attacks}.",
			"move_hint_blocked": "{piece} заблокирована."
	},
	"de": {
		"main_title": "Royal Lines",
		"main_subtitle": "Schachzüge. Lines-Rätsel. 5 in einer Reihe.",
		"play": "Spielen",
		"how_to_play": "Anleitung",
		"settings": "Einstellungen",
		"quit": "Beenden",
		"back": "Zurück",
		"close": "Schließen",
		"sound": "Ton",
		"vibration": "Vibration",
		"theme": "Design",
		"language": "Sprache",
		"on": "Ein",
		"off": "Aus",
		"sound_on": "Ton: Ein",
		"sound_off": "Ton: Aus",
		"vibration_on": "Vibration: Ein",
		"vibration_off": "Vibration: Aus",
		"theme_default": "Standard",
		"theme_neon": "Neon",
		"how_to_play_text": "[b]Ziel:[/b]\nBewege Schachfiguren, um Linien aus 5 oder mehr passenden Figuren zu bilden, sie zu räumen und Punkte zu sammeln.\n\n[b]Bewegung:[/b]\n- Klicke eine Figur an, um sie auszuwählen\n- Gültige leere Felder werden markiert\n- Klicke ein markiertes Feld an, um zu ziehen\n- Figuren bewegen sich nach schachinspirierten Regeln\n\n[b]Linien räumen:[/b]\n[color=RED]Farblinie:[/color] 5 oder mehr Figuren derselben Farbe\n[color=GREEN]Typenlinie:[/color] 5 oder mehr Figuren desselben Typs\n[color=YELLOW]Kombination:[/color] Eine Linie passt nach Farbe und Typ\n\n[b]Rundenablauf:[/b]\n- Du startest mit 3 zufälligen Figuren\n- Nach jedem Zug erscheinen 3 weitere Figuren\n- Wenn das Brett voll ist oder keine sinnvollen Züge bleiben, endet das Spiel\n\n[b]Koenigreich-Abzeichen:[/b]",
		"badge_progression_summary": "Hoechste abgeschlossene Stufe im Koenigreich.\nLeer / Bronze / Silber / Gold",
		"badge_tactical_summary": "Misst, wie gut du ohne Figurenopfer bestehst.\nLeer / Bronze / Silber / Gold",
		"badge_campaign_summary": "Deine Kampagnenleistung.\nLeer / Bronze / Silber / Gold",
		"score": "Punkte",
		"best": "Bestwert",
		"your_best": "Dein Bestwert",
		"final_score": "Endpunktzahl",
		"game_paused": "Spiel pausiert.",
		"resume": "Fortsetzen",
		"reset": "Zurücksetzen",
		"main_menu": "Hauptmenü",
		"game_over": "SPIEL VORBEI",
		"session_complete": "Sitzung abgeschlossen",
		"play_again": "Erneut spielen",
		"level_start_default": "Level #{number} startet",
		"level_start_default_theme": "Der Kampf beginnt!",
		"level_start_neon_theme": "Bringen wir Licht ins Dunkel.",
		"level_complete": "Level {number} abgeschlossen!",
		"level_complete_short": "Level abgeschlossen",
		"trap_disappeared": "Gefangen von {trap} -{cost} :(",
		"trap_swallow_name": "Großer Sumpf",
		"trap_swallow_description": "Ich kaue dich durch und spucke dich wieder aus.",
		"sacrifice": "{piece}-Opfer",
		"piece_pawn": "Bauer",
		"piece_knight": "Springer",
		"piece_bishop": "Läufer",
		"piece_rook": "Turm",
		"piece_queen": "Dame",
		"piece_king": "König",
		"piece_generic": "Figur",
		"color_line": "Farblinie",
		"row_6": "6 in Reihe",
		"row_7": "7 in Reihe",
		"row_8": "8 in Reihe",
		"long_line": "Lange Linie",
		"pawn_formation": "Bauernformation",
		"knight_line": "Springerlinie",
		"bishop_chain": "Läuferkette",
		"rook_formation": "Turmformation",
		"queen_formation": "Damenformation",
		"typed_line": "Typenlinie",
		"united_knights": "Vereinte Springer",
		"united_bishops": "Vereinte Läufer",
		"united_rooks": "Vereinte Türme",
		"united_forces": "Vereinte Kräfte",
			"move_hint_move_one": "auf 1 Feld ziehen",
			"move_hint_move_many": "auf {count} Felder ziehen",
			"move_hint_attack_one": "1 Figur angreifen",
			"move_hint_attack_many": "{count} Figuren angreifen",
			"move_hint_move_only": "{piece} kann {moves}.",
			"move_hint_attack_only": "{piece} kann {attacks}.",
			"move_hint_move_attack": "{piece} kann {moves} und {attacks}.",
			"move_hint_blocked": "{piece} ist blockiert."
	},
	"fr": {
		"main_title": "Royal Lines",
		"main_subtitle": "Mouvements d'échecs. Puzzle Lines. 5 à la suite.",
		"play": "Jouer",
		"how_to_play": "Comment jouer",
		"settings": "Paramètres",
		"quit": "Quitter",
		"back": "Retour",
		"close": "Fermer",
		"sound": "Son",
		"vibration": "Vibration",
		"theme": "Thème",
		"language": "Langue",
		"on": "Activé",
		"off": "Désactivé",
		"sound_on": "Son : activé",
		"sound_off": "Son : désactivé",
		"vibration_on": "Vibration : activée",
		"vibration_off": "Vibration : désactivée",
		"theme_default": "Par défaut",
		"theme_neon": "Néon",
		"how_to_play_text": "[b]But :[/b]\nDéplacez les pièces d'échecs pour créer des lignes de 5 pièces correspondantes ou plus, les effacer et marquer des points.\n\n[b]Déplacement :[/b]\n- Cliquez sur une pièce pour la sélectionner\n- Les cases vides valides sont surlignées\n- Cliquez sur une case surlignée pour vous déplacer\n- Les pièces suivent des règles inspirées des échecs\n\n[b]Effacer des lignes :[/b]\n[color=RED]Ligne de couleur :[/color] 5 pièces ou plus de la même couleur\n[color=GREEN]Ligne de type :[/color] 5 pièces ou plus du même type\n[color=YELLOW]Combo :[/color] une ligne correspond à la fois par couleur et par type\n\n[b]Déroulement :[/b]\n- Vous commencez avec 3 pièces aléatoires\n- Après chaque déplacement, 3 nouvelles pièces apparaissent\n- Si le plateau est plein ou qu'il n'y a plus de coup utile, la partie se termine\n\n[b]Insignes du royaume :[/b]",
		"badge_progression_summary": "Niveau maximum termine dans le royaume.\nVide / Bronze / Argent / Or",
		"badge_tactical_summary": "Mesure votre tenue sans sacrifier de pieces.\nVide / Bronze / Argent / Or",
		"badge_campaign_summary": "Votre performance en campagne.\nVide / Bronze / Argent / Or",
		"score": "Score",
		"best": "Meilleur",
		"your_best": "Votre meilleur",
		"final_score": "Score final",
		"game_paused": "Jeu en pause.",
		"resume": "Reprendre",
		"reset": "Réinitialiser",
		"main_menu": "Menu principal",
		"game_over": "PARTIE TERMINÉE",
		"session_complete": "Session terminée",
		"play_again": "Rejouer",
		"level_start_default": "Début du niveau #{number}",
		"level_start_default_theme": "Que le combat commence !",
		"level_start_neon_theme": "Faisons la lumière dans l'obscurité.",
		"level_complete": "Niveau {number} terminé !",
		"level_complete_short": "Niveau terminé",
		"trap_disappeared": "Piégé par {trap} -{cost} :(",
		"trap_swallow_name": "Grand marécage",
		"trap_swallow_description": "Je vais te mâcher et te recracher.",
		"sacrifice": "Sacrifice de {piece}",
		"piece_pawn": "Pion",
		"piece_knight": "Cavalier",
		"piece_bishop": "Fou",
		"piece_rook": "Tour",
		"piece_queen": "Dame",
		"piece_king": "Roi",
		"piece_generic": "Pièce",
		"color_line": "Ligne de couleur",
		"row_6": "6 à la suite",
		"row_7": "7 à la suite",
		"row_8": "8 à la suite",
		"long_line": "Longue ligne",
		"pawn_formation": "Formation de pions",
		"knight_line": "Ligne de cavaliers",
		"bishop_chain": "Chaîne de fous",
		"rook_formation": "Formation de tours",
		"queen_formation": "Formation de dames",
		"typed_line": "Ligne de type",
		"united_knights": "Cavaliers unis",
		"united_bishops": "Fous unis",
		"united_rooks": "Tours unies",
		"united_forces": "Forces unies",
			"move_hint_move_one": "se déplacer vers 1 case",
			"move_hint_move_many": "se déplacer vers {count} cases",
			"move_hint_attack_one": "attaquer 1 pièce",
			"move_hint_attack_many": "attaquer {count} pièces",
			"move_hint_move_only": "{piece} peut {moves}.",
			"move_hint_attack_only": "{piece} peut {attacks}.",
			"move_hint_move_attack": "{piece} peut {moves} et {attacks}.",
			"move_hint_blocked": "{piece} est bloquée."
	},
	"es": {
		"main_title": "Royal Lines",
		"main_subtitle": "Movimiento de ajedrez. Puzzle Lines. 5 en línea.",
		"play": "Jugar",
		"how_to_play": "Cómo jugar",
		"settings": "Ajustes",
		"quit": "Salir",
		"back": "Atrás",
		"close": "Cerrar",
		"sound": "Sonido",
		"vibration": "Vibración",
		"theme": "Tema",
		"language": "Idioma",
		"on": "Activado",
		"off": "Desactivado",
		"sound_on": "Sonido: activado",
		"sound_off": "Sonido: desactivado",
		"vibration_on": "Vibración: activada",
		"vibration_off": "Vibración: desactivada",
		"theme_default": "Predeterminado",
		"theme_neon": "Neón",
		"how_to_play_text": "[b]Objetivo:[/b]\nMueve piezas de ajedrez para crear líneas de 5 o más piezas coincidentes, eliminarlas y ganar puntos.\n\n[b]Movimiento:[/b]\n- Haz clic en una pieza para seleccionarla\n- Las casillas vacías válidas se resaltan\n- Haz clic en una casilla resaltada para mover\n- Las piezas se mueven con reglas inspiradas en el ajedrez\n\n[b]Eliminar líneas:[/b]\n[color=RED]Línea de color:[/color] 5 o más piezas del mismo color\n[color=GREEN]Línea de tipo:[/color] 5 o más piezas del mismo tipo\n[color=YELLOW]Combo:[/color] una línea coincide por color y por tipo\n\n[b]Flujo del turno:[/b]\n- Empiezas con 3 piezas aleatorias\n- Después de cada movimiento aparecen 3 piezas más\n- Si el tablero se llena o no quedan movimientos útiles, la partida termina\n\n[b]Insignias del reino:[/b]",
		"badge_progression_summary": "Nivel maximo completado en el reino.\nVacio / Bronce / Plata / Oro",
		"badge_tactical_summary": "Mide que tan bien resistes sin sacrificar piezas.\nVacio / Bronce / Plata / Oro",
		"badge_campaign_summary": "Tu rendimiento en campanas.\nVacio / Bronce / Plata / Oro",
		"score": "Puntuación",
		"best": "Récord",
		"your_best": "Tu mejor",
		"final_score": "Puntuación final",
		"game_paused": "Juego en pausa.",
		"resume": "Continuar",
		"reset": "Reiniciar",
		"main_menu": "Menú principal",
		"game_over": "FIN DE LA PARTIDA",
		"session_complete": "Sesión completada",
		"play_again": "Jugar otra vez",
		"level_start_default": "Comienza el nivel #{number}",
		"level_start_default_theme": "¡Que empiece la batalla!",
		"level_start_neon_theme": "Arrojemos algo de luz sobre la oscuridad.",
		"level_complete": "¡Nivel {number} completado!",
		"level_complete_short": "Nivel completado",
		"trap_disappeared": "Atrapado por {trap} -{cost} :(",
		"trap_swallow_name": "Gran ciénaga",
		"trap_swallow_description": "Te masticaré y te escupiré.",
		"sacrifice": "Sacrificio de {piece}",
		"piece_pawn": "Peón",
		"piece_knight": "Caballo",
		"piece_bishop": "Alfil",
		"piece_rook": "Torre",
		"piece_queen": "Dama",
		"piece_king": "Rey",
		"piece_generic": "Pieza",
		"color_line": "Línea de color",
		"row_6": "6 en línea",
		"row_7": "7 en línea",
		"row_8": "8 en línea",
		"long_line": "Línea larga",
		"pawn_formation": "Formación de peones",
		"knight_line": "Línea de caballos",
		"bishop_chain": "Cadena de alfiles",
		"rook_formation": "Formación de torres",
		"queen_formation": "Formación de damas",
		"typed_line": "Línea de tipo",
		"united_knights": "Caballos unidos",
		"united_bishops": "Alfiles unidos",
		"united_rooks": "Torres unidas",
		"united_forces": "Fuerzas unidas",
			"move_hint_move_one": "moverse a 1 casilla",
			"move_hint_move_many": "moverse a {count} casillas",
			"move_hint_attack_one": "atacar 1 pieza",
			"move_hint_attack_many": "atacar {count} piezas",
			"move_hint_move_only": "{piece} puede {moves}.",
			"move_hint_attack_only": "{piece} puede {attacks}.",
			"move_hint_move_attack": "{piece} puede {moves} y {attacks}.",
			"move_hint_blocked": "{piece} está bloqueada."
	},
	"fi": {
		"main_title": "Royal Lines",
		"main_subtitle": "Shakkisiirrot. Lines-pulma. 5 peräkkäin.",
		"play": "Pelaa",
		"how_to_play": "Ohjeet",
		"settings": "Asetukset",
		"quit": "Lopeta",
		"back": "Takaisin",
		"close": "Sulje",
		"sound": "Äänet",
		"vibration": "Värinä",
		"theme": "Teema",
		"language": "Kieli",
		"on": "Päällä",
		"off": "Pois",
		"sound_on": "Äänet: päällä",
		"sound_off": "Äänet: pois",
		"vibration_on": "Värinä: päällä",
		"vibration_off": "Värinä: pois",
		"theme_default": "Oletus",
		"theme_neon": "Neon",
		"how_to_play_text": "[b]Tavoite:[/b]\nSiirrä shakkinappuloita ja muodosta vähintään 5 samanlaisen nappulan linjoja, poista ne ja kerää pisteitä.\n\n[b]Liikkuminen:[/b]\n- Valitse nappula klikkaamalla sitä\n- Mahdolliset tyhjät ruudut korostetaan\n- Siirrä klikkaamalla korostettua ruutua\n- Nappulat liikkuvat shakkia mukailevilla säännöillä\n\n[b]Linjojen poistaminen:[/b]\n[color=RED]Värilinja:[/color] vähintään 5 samanväristä nappulaa\n[color=GREEN]Tyyppilinja:[/color] vähintään 5 saman tyyppistä nappulaa\n[color=YELLOW]Kombo:[/color] linja täsmää sekä värin että tyypin mukaan\n\n[b]Vuoron kulku:[/b]\n- Aloitat 3 satunnaisella nappulalla\n- Jokaisen siirron jälkeen ilmestyy 3 uutta nappulaa\n- Jos lauta täyttyy tai hyödyllisiä siirtoja ei ole, peli päättyy\n\n[b]Valtakunnan merkit:[/b]",
		"badge_progression_summary": "Korkein suoritettu taso valtakunnassa.\nTyhja / Pronssi / Hopea / Kulta",
		"badge_tactical_summary": "Mittaa, kuinka hyvin selviat ilman nappuloiden uhraamista.\nTyhja / Pronssi / Hopea / Kulta",
		"badge_campaign_summary": "Kampanjasuorituksesi.\nTyhja / Pronssi / Hopea / Kulta",
		"score": "Pisteet",
		"best": "Ennätys",
		"your_best": "Paras tuloksesi",
		"final_score": "Lopputulos",
		"game_paused": "Peli keskeytetty.",
		"resume": "Jatka",
		"reset": "Nollaa",
		"main_menu": "Päävalikko",
		"game_over": "PELI PÄÄTTYI",
		"session_complete": "Pelikerta päättyi",
		"play_again": "Pelaa uudelleen",
		"level_start_default": "Taso #{number} alkaa",
		"level_start_default_theme": "Taistelu alkakoon!",
		"level_start_neon_theme": "Valaistaan pimeyttä.",
		"level_complete": "Taso {number} valmis!",
		"level_complete_short": "Taso valmis",
		"trap_disappeared": "Ansassa {trap} -{cost} :(",
		"trap_swallow_name": "Suuri suo",
		"trap_swallow_description": "Pureskelen sinut ja sylkäisen ulos.",
		"sacrifice": "{piece}-uhraus",
		"piece_pawn": "Sotilas",
		"piece_knight": "Ratsu",
		"piece_bishop": "Lähetti",
		"piece_rook": "Torni",
		"piece_queen": "Kuningatar",
		"piece_king": "Kuningas",
		"piece_generic": "Nappula",
		"color_line": "Värilinja",
		"row_6": "6 peräkkäin",
		"row_7": "7 peräkkäin",
		"row_8": "8 peräkkäin",
		"long_line": "Pitkä linja",
		"pawn_formation": "Sotilasmuodostelma",
		"knight_line": "Ratsulinja",
		"bishop_chain": "Lähettiketju",
		"rook_formation": "Tornimuodostelma",
		"queen_formation": "Kuningatarmuodostelma",
		"typed_line": "Tyyppilinja",
		"united_knights": "Yhdistetyt ratsut",
		"united_bishops": "Yhdistetyt lähetit",
		"united_rooks": "Yhdistetyt tornit",
		"united_forces": "Yhdistetyt voimat",
			"move_hint_move_one": "siirtyä 1 ruutuun",
			"move_hint_move_many": "siirtyä {count} ruutuun",
			"move_hint_attack_one": "hyökätä 1 nappulaan",
			"move_hint_attack_many": "hyökätä {count} nappulaan",
			"move_hint_move_only": "{piece} voi {moves}.",
			"move_hint_attack_only": "{piece} voi {attacks}.",
			"move_hint_move_attack": "{piece} voi {moves} ja {attacks}.",
			"move_hint_blocked": "{piece} on jumissa."
	},
	"sv": {
		"main_title": "Royal Lines",
		"main_subtitle": "Schackdrag. Lines-pussel. 5 i rad.",
		"play": "Spela",
		"how_to_play": "Så spelar du",
		"settings": "Inställningar",
		"quit": "Avsluta",
		"back": "Tillbaka",
		"close": "Stäng",
		"sound": "Ljud",
		"vibration": "Vibration",
		"theme": "Tema",
		"language": "Språk",
		"on": "På",
		"off": "Av",
		"sound_on": "Ljud: på",
		"sound_off": "Ljud: av",
		"vibration_on": "Vibration: på",
		"vibration_off": "Vibration: av",
		"theme_default": "Standard",
		"theme_neon": "Neon",
		"how_to_play_text": "[b]Mål:[/b]\nFlytta schackpjäser för att skapa linjer med 5 eller fler matchande pjäser, rensa dem och få poäng.\n\n[b]Förflyttning:[/b]\n- Klicka på en pjäs för att välja den\n- Giltiga tomma rutor markeras\n- Klicka på en markerad ruta för att flytta\n- Pjäserna rör sig enligt schackinspirerade regler\n\n[b]Rensa linjer:[/b]\n[color=RED]Färglinje:[/color] 5 eller fler pjäser med samma färg\n[color=GREEN]Typlinje:[/color] 5 eller fler pjäser av samma typ\n[color=YELLOW]Kombination:[/color] en linje matchar både färg och typ\n\n[b]Turflöde:[/b]\n- Du börjar med 3 slumpmässiga pjäser\n- Efter varje drag skapas 3 nya pjäser\n- Om brädet fylls eller inga meningsfulla drag finns kvar tar spelet slut\n\n[b]Rikets marken:[/b]",
		"badge_progression_summary": "Hogsta avslutade niva i riket.\nTom / Brons / Silver / Guld",
		"badge_tactical_summary": "Mäter hur bra du klarar dig utan att offra pjäser.\nTom / Brons / Silver / Guld",
		"badge_campaign_summary": "Din kampanjprestation.\nTom / Brons / Silver / Guld",
		"score": "Poäng",
		"best": "Bästa",
		"your_best": "Ditt basta",
		"final_score": "Slutpoäng",
		"game_paused": "Spelet är pausat.",
		"resume": "Fortsätt",
		"reset": "Återställ",
		"main_menu": "Huvudmeny",
		"game_over": "SPELET ÄR SLUT",
		"session_complete": "Omgången är klar",
		"play_again": "Spela igen",
		"level_start_default": "Nivå #{number} startar",
		"level_start_default_theme": "Låt kampen börja!",
		"level_start_neon_theme": "Låt oss kasta ljus över mörkret.",
		"level_complete": "Nivå {number} klar!",
		"level_complete_short": "Nivå klar",
		"trap_disappeared": "Fångad av {trap} -{cost} :(",
		"trap_swallow_name": "Stora träsket",
		"trap_swallow_description": "Jag tuggar dig och spottar ut dig.",
		"sacrifice": "{piece}-offer",
		"piece_pawn": "Bonde",
		"piece_knight": "Springare",
		"piece_bishop": "Löpare",
		"piece_rook": "Torn",
		"piece_queen": "Dam",
		"piece_king": "Kung",
		"piece_generic": "Pjäs",
		"color_line": "Färglinje",
		"row_6": "6 i rad",
		"row_7": "7 i rad",
		"row_8": "8 i rad",
		"long_line": "Lång linje",
		"pawn_formation": "Bondeformation",
		"knight_line": "Springarlinje",
		"bishop_chain": "Löparkedja",
		"rook_formation": "Tornformation",
		"queen_formation": "Damformation",
		"typed_line": "Typlinje",
		"united_knights": "Förenade springare",
		"united_bishops": "Förenade löpare",
		"united_rooks": "Förenade torn",
		"united_forces": "Förenade styrkor",
			"move_hint_move_one": "flytta till 1 ruta",
			"move_hint_move_many": "flytta till {count} rutor",
			"move_hint_attack_one": "anfalla 1 pjäs",
			"move_hint_attack_many": "anfalla {count} pjäser",
			"move_hint_move_only": "{piece} kan {moves}.",
			"move_hint_attack_only": "{piece} kan {attacks}.",
			"move_hint_move_attack": "{piece} kan {moves} och {attacks}.",
			"move_hint_blocked": "{piece} är blockerad."
	}
}

func get_available_language_codes() -> PackedStringArray:
	return PackedStringArray(["en", "ru", "de", "fr", "es", "fi", "sv"])

func get_language_display_name(language_code: String) -> String:
	return str(LANGUAGE_NAMES.get(language_code, LANGUAGE_NAMES[DEFAULT_LANGUAGE_CODE]))

func t(key: String) -> String:
	var language_code := Settings.language_code if Settings != null else DEFAULT_LANGUAGE_CODE
	var table: Dictionary = TRANSLATIONS.get(language_code, TRANSLATIONS[DEFAULT_LANGUAGE_CODE])
	if table.has(key):
		return str(table[key])
	return str(TRANSLATIONS[DEFAULT_LANGUAGE_CODE].get(key, key))

func tf(key: String, values: Dictionary) -> String:
	var text := t(key)
	for value_key in values.keys():
		text = text.replace("{" + str(value_key) + "}", str(values[value_key]))
	return text
